//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VersionInfo", Namespace="http://schemas.datacontract.org/2004/07/N3.Shared.Core")]
    public partial class VersionInfo : object
    {
        
        private string DatabaseVersionField;
        
        private string ServiceVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseVersion
        {
            get
            {
                return this.DatabaseVersionField;
            }
            set
            {
                this.DatabaseVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceVersion
        {
            get
            {
                return this.ServiceVersionField;
            }
            set
            {
                this.ServiceVersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class PatientDto : object
    {
        
        private PixService.AddressDto[] AddressesField;
        
        private System.DateTime BirthDateField;
        
        private PixService.BirthPlaceDto BirthPlaceField;
        
        private PixService.ContactPersonDto ContactPersonField;
        
        private PixService.ContactDto[] ContactsField;
        
        private System.Nullable<System.DateTime> DeathTimeField;
        
        private PixService.DocumentDto[] DocumentsField;
        
        private string FamilyNameField;
        
        private string GivenNameField;
        
        private System.Nullable<byte> IdBloodTypeField;
        
        private string IdGlobalField;
        
        private System.Nullable<byte> IdLivingAreaTypeField;
        
        private string IdPatientMISField;
        
        private bool IsVipField;
        
        private PixService.JobDto JobField;
        
        private string MiddleNameField;
        
        private PixService.PrivilegeDto PrivilegeField;
        
        private byte SexField;
        
        private System.Nullable<byte> SocialGroupField;
        
        private string SocialStatusField;
        
        private string UseNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.AddressDto[] Addresses
        {
            get
            {
                return this.AddressesField;
            }
            set
            {
                this.AddressesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.BirthPlaceDto BirthPlace
        {
            get
            {
                return this.BirthPlaceField;
            }
            set
            {
                this.BirthPlaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.ContactPersonDto ContactPerson
        {
            get
            {
                return this.ContactPersonField;
            }
            set
            {
                this.ContactPersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.ContactDto[] Contacts
        {
            get
            {
                return this.ContactsField;
            }
            set
            {
                this.ContactsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeathTime
        {
            get
            {
                return this.DeathTimeField;
            }
            set
            {
                this.DeathTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.DocumentDto[] Documents
        {
            get
            {
                return this.DocumentsField;
            }
            set
            {
                this.DocumentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName
        {
            get
            {
                return this.FamilyNameField;
            }
            set
            {
                this.FamilyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IdBloodType
        {
            get
            {
                return this.IdBloodTypeField;
            }
            set
            {
                this.IdBloodTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdGlobal
        {
            get
            {
                return this.IdGlobalField;
            }
            set
            {
                this.IdGlobalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IdLivingAreaType
        {
            get
            {
                return this.IdLivingAreaTypeField;
            }
            set
            {
                this.IdLivingAreaTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPatientMIS
        {
            get
            {
                return this.IdPatientMISField;
            }
            set
            {
                this.IdPatientMISField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVip
        {
            get
            {
                return this.IsVipField;
            }
            set
            {
                this.IsVipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.JobDto Job
        {
            get
            {
                return this.JobField;
            }
            set
            {
                this.JobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.PrivilegeDto Privilege
        {
            get
            {
                return this.PrivilegeField;
            }
            set
            {
                this.PrivilegeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> SocialGroup
        {
            get
            {
                return this.SocialGroupField;
            }
            set
            {
                this.SocialGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialStatus
        {
            get
            {
                return this.SocialStatusField;
            }
            set
            {
                this.SocialStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseName
        {
            get
            {
                return this.UseNameField;
            }
            set
            {
                this.UseNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BirthPlaceDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class BirthPlaceDto : object
    {
        
        private string CityField;
        
        private string CountryField;
        
        private string RegionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactPersonDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class ContactPersonDto : object
    {
        
        private PixService.ContactDto[] ContactListField;
        
        private string FamilyNameField;
        
        private string GivenNameField;
        
        private string IdPersonMisField;
        
        private byte IdRelationTypeField;
        
        private string MiddleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.ContactDto[] ContactList
        {
            get
            {
                return this.ContactListField;
            }
            set
            {
                this.ContactListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FamilyName
        {
            get
            {
                return this.FamilyNameField;
            }
            set
            {
                this.FamilyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPersonMis
        {
            get
            {
                return this.IdPersonMisField;
            }
            set
            {
                this.IdPersonMisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdRelationType
        {
            get
            {
                return this.IdRelationTypeField;
            }
            set
            {
                this.IdRelationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class JobDto : object
    {
        
        private string CompanyNameField;
        
        private System.Nullable<System.DateTime> DateEndField;
        
        private System.Nullable<System.DateTime> DateStartField;
        
        private string OgrnCodeField;
        
        private string PositionField;
        
        private string SphereField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName
        {
            get
            {
                return this.CompanyNameField;
            }
            set
            {
                this.CompanyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateEnd
        {
            get
            {
                return this.DateEndField;
            }
            set
            {
                this.DateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateStart
        {
            get
            {
                return this.DateStartField;
            }
            set
            {
                this.DateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrnCode
        {
            get
            {
                return this.OgrnCodeField;
            }
            set
            {
                this.OgrnCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sphere
        {
            get
            {
                return this.SphereField;
            }
            set
            {
                this.SphereField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrivilegeDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class PrivilegeDto : object
    {
        
        private string CommentField;
        
        private System.DateTime DateEndField;
        
        private System.DateTime DateStartField;
        
        private string DisabilityDegreeField;
        
        private System.Nullable<byte> IdDisabilityTypeField;
        
        private byte IdPrivilegeTypeField;
        
        private bool IsMainField;
        
        private string MkbCodeField;
        
        private PixService.DocumentDto PrivilegeDocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnd
        {
            get
            {
                return this.DateEndField;
            }
            set
            {
                this.DateEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateStart
        {
            get
            {
                return this.DateStartField;
            }
            set
            {
                this.DateStartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisabilityDegree
        {
            get
            {
                return this.DisabilityDegreeField;
            }
            set
            {
                this.DisabilityDegreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> IdDisabilityType
        {
            get
            {
                return this.IdDisabilityTypeField;
            }
            set
            {
                this.IdDisabilityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdPrivilegeType
        {
            get
            {
                return this.IdPrivilegeTypeField;
            }
            set
            {
                this.IdPrivilegeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMain
        {
            get
            {
                return this.IsMainField;
            }
            set
            {
                this.IsMainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MkbCode
        {
            get
            {
                return this.MkbCodeField;
            }
            set
            {
                this.MkbCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PixService.DocumentDto PrivilegeDocument
        {
            get
            {
                return this.PrivilegeDocumentField;
            }
            set
            {
                this.PrivilegeDocumentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class AddressDto : object
    {
        
        private string AppartmentField;
        
        private string BuildingField;
        
        private string CityField;
        
        private string GeoDataField;
        
        private byte IdAddressTypeField;
        
        private System.Nullable<int> PostalCodeField;
        
        private string StreetField;
        
        private string StringAddressField;
        
        private string RegionField;
        
        private byte AddressTypeCodingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Appartment
        {
            get
            {
                return this.AppartmentField;
            }
            set
            {
                this.AppartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeoData
        {
            get
            {
                return this.GeoDataField;
            }
            set
            {
                this.GeoDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdAddressType
        {
            get
            {
                return this.IdAddressTypeField;
            }
            set
            {
                this.IdAddressTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringAddress
        {
            get
            {
                return this.StringAddressField;
            }
            set
            {
                this.StringAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public byte AddressTypeCoding
        {
            get
            {
                return this.AddressTypeCodingField;
            }
            set
            {
                this.AddressTypeCodingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class ContactDto : object
    {
        
        private string ContactValueField;
        
        private byte IdContactTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactValue
        {
            get
            {
                return this.ContactValueField;
            }
            set
            {
                this.ContactValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte IdContactType
        {
            get
            {
                return this.IdContactTypeField;
            }
            set
            {
                this.IdContactTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentDto", Namespace="http://schemas.datacontract.org/2004/07/EMKService.Data.Dto")]
    public partial class DocumentDto : object
    {
        
        private string DocNField;
        
        private string DocSField;
        
        private string DocumentNameField;
        
        private System.Nullable<System.DateTime> ExpiredDateField;
        
        private short IdDocumentTypeField;
        
        private string IdProviderField;
        
        private System.Nullable<System.DateTime> IssuedDateField;
        
        private string ProviderNameField;
        
        private string RegionCodeField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocN
        {
            get
            {
                return this.DocNField;
            }
            set
            {
                this.DocNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocS
        {
            get
            {
                return this.DocSField;
            }
            set
            {
                this.DocSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentName
        {
            get
            {
                return this.DocumentNameField;
            }
            set
            {
                this.DocumentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpiredDate
        {
            get
            {
                return this.ExpiredDateField;
            }
            set
            {
                this.ExpiredDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdDocumentType
        {
            get
            {
                return this.IdDocumentTypeField;
            }
            set
            {
                this.IdDocumentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvider
        {
            get
            {
                return this.IdProviderField;
            }
            set
            {
                this.IdProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssuedDate
        {
            get
            {
                return this.IssuedDateField;
            }
            set
            {
                this.IssuedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
    public partial class RequestFault : object
    {
        
        private string PropertyNameField;
        
        private string MessageField;
        
        private int ErrorCodeField;
        
        private PixService.RequestFault[] ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public PixService.RequestFault[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceType", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Domain.Enums")]
    public enum SourceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reg = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fed = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PixService.IPixService")]
    public interface IPixService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/GetVersion", ReplyAction="http://tempuri.org/IPixService/GetVersionResponse")]
        System.Threading.Tasks.Task<PixService.VersionInfo> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/AddPatient", ReplyAction="http://tempuri.org/IPixService/AddPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/AddPatientRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/AddPatientListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task AddPatientAsync(string guid, string idLPU, PixService.PatientDto patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/AddPatientAndGetId", ReplyAction="http://tempuri.org/IPixService/AddPatientAndGetIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/AddPatientAndGetIdRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/AddPatientAndGetIdListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task<System.Guid> AddPatientAndGetIdAsync(string guid, string idLPU, PixService.PatientDto patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/UpdatePatient", ReplyAction="http://tempuri.org/IPixService/UpdatePatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/UpdatePatientRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/UpdatePatientListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task UpdatePatientAsync(string guid, string idLPU, PixService.PatientDto patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/UpdatePatientAndGetId", ReplyAction="http://tempuri.org/IPixService/UpdatePatientAndGetIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/UpdatePatientAndGetIdRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/UpdatePatientAndGetIdListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task<System.Guid> UpdatePatientAndGetIdAsync(string guid, string idLPU, PixService.PatientDto patient);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/GetPatient", ReplyAction="http://tempuri.org/IPixService/GetPatientResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/GetPatientRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/GetPatientListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task<PixService.PatientDto[]> GetPatientAsync(string guid, string idLPU, PixService.PatientDto patient, PixService.SourceType idSource);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPixService/GetPatientByGlobalId", ReplyAction="http://tempuri.org/IPixService/GetPatientByGlobalIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault), Action="http://tempuri.org/IPixService/GetPatientByGlobalIdRequestFaultFault", Name="RequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        [System.ServiceModel.FaultContractAttribute(typeof(PixService.RequestFault[]), Action="http://tempuri.org/IPixService/GetPatientByGlobalIdListOf_RequestFaultFault", Name="ArrayOfRequestFault", Namespace="http://schemas.datacontract.org/2004/07/N3.EMK.Dto.Common")]
        System.Threading.Tasks.Task<PixService.PatientDto> GetPatientByGlobalIdAsync(string guid, string patientId, string idLpu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IPixServiceChannel : PixService.IPixService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class PixServiceClient : System.ServiceModel.ClientBase<PixService.IPixService>, PixService.IPixService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PixServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PixServiceClient.GetBindingForEndpoint(endpointConfiguration), PixServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PixServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PixServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PixServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PixService.VersionInfo> GetVersionAsync()
        {
            return base.Channel.GetVersionAsync();
        }
        
        public System.Threading.Tasks.Task AddPatientAsync(string guid, string idLPU, PixService.PatientDto patient)
        {
            return base.Channel.AddPatientAsync(guid, idLPU, patient);
        }
        
        public System.Threading.Tasks.Task<System.Guid> AddPatientAndGetIdAsync(string guid, string idLPU, PixService.PatientDto patient)
        {
            return base.Channel.AddPatientAndGetIdAsync(guid, idLPU, patient);
        }
        
        public System.Threading.Tasks.Task UpdatePatientAsync(string guid, string idLPU, PixService.PatientDto patient)
        {
            return base.Channel.UpdatePatientAsync(guid, idLPU, patient);
        }
        
        public System.Threading.Tasks.Task<System.Guid> UpdatePatientAndGetIdAsync(string guid, string idLPU, PixService.PatientDto patient)
        {
            return base.Channel.UpdatePatientAndGetIdAsync(guid, idLPU, patient);
        }
        
        public System.Threading.Tasks.Task<PixService.PatientDto[]> GetPatientAsync(string guid, string idLPU, PixService.PatientDto patient, PixService.SourceType idSource)
        {
            return base.Channel.GetPatientAsync(guid, idLPU, patient, idSource);
        }
        
        public System.Threading.Tasks.Task<PixService.PatientDto> GetPatientByGlobalIdAsync(string guid, string patientId, string idLpu)
        {
            return base.Channel.GetPatientByGlobalIdAsync(guid, patientId, idLpu);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPixService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Soap12_PixService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPixService))
            {
                return new System.ServiceModel.EndpointAddress("http://b2b-demo.n3health.ru/emk/PixService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.Soap12_PixService))
            {
                return new System.ServiceModel.EndpointAddress("http://b2b-demo.n3health.ru/emk/PixService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPixService,
            
            Soap12_PixService,
        }
    }
}
